# Generated by Django 5.0.1 on 2024-01-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages_to_me',
        ),
    ]
