# Generated by Django 5.0.1 on 2024-01-26 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_message_options_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sendDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 22, 48, 41, 262623), editable=False),
        ),
    ]
