# Generated by Django 5.0.1 on 2024-01-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_message_senddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
