# Generated by Django 5.0.1 on 2024-01-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='motive',
            field=models.CharField(max_length=64),
        ),
    ]
