# Generated by Django 5.0.1 on 2024-01-16 17:03

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('keepChecked', models.BooleanField(blank=True, default=True, verbose_name='Garder connecté')),
                ('joinNewsletter', models.BooleanField(blank=True, default=True, verbose_name='Abonner à la NewsLetter')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'blogUser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(max_length=470, verbose_name='Description de la catégorie')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image de la catégorie')),
                ('imageAlt', models.CharField(default='Auteur Anonyme', max_length=32, verbose_name="Description de l'image")),
                ('imageAuthor', models.CharField(blank=True, max_length=32, null=True, verbose_name="Auteur de l'image")),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=16)),
                ('saveDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hashtag',
                'verbose_name_plural': 'Hashtags',
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='WhatPeopleSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=246)),
                ('whoSaid', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'opinion_on_blog',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(blank=True, editable=False, max_length=130, unique=True, verbose_name='Slug')),
                ('sumItUp', models.TextField(max_length=320, verbose_name='Une courte introduction')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image Principale')),
                ('imageAlt', models.CharField(max_length=100, verbose_name="Description de l'image")),
                ('imageAuthor', models.CharField(blank=True, default='Auteur Anonyme', max_length=64, null=True, verbose_name="Auteur de l'image")),
                ('saveDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, to='post.bloguser', verbose_name='Nombre de Likes')),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Les Catégories')),
                ('hashtags', models.ManyToManyField(to='post.hashtags', verbose_name='Les hashtags')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'Aricles',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=216, null=True, verbose_name='Commentaire')),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('canBePosted', models.BooleanField(default=False, verbose_name='Peut-être posté')),
                ('whichArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.article', verbose_name='Article')),
                ('whoPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.bloguser', verbose_name='Commentateur')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'comment',
            },
        ),
    ]
