# Generated by Django 4.2.3 on 2024-01-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='whoPost',
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
