# Generated by Django 4.2.3 on 2024-01-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_bloguser_article_likes_comment_whopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageAlt',
            field=models.CharField(default='Auteur Anonyme', max_length=100, verbose_name="Description de l'image"),
        ),
    ]
