# Generated by Django 5.0.1 on 2024-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(related_name='article_hashtags', to='post.hashtags', verbose_name='Les hashtags'),
        ),
    ]
