# Generated by Django 4.2.3 on 2024-01-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_article_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articleAuthor', to='post.bloguser'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(to='post.hashtags', verbose_name='Les hashtags'),
        ),
    ]
