# Generated by Django 4.2.3 on 2024-01-22 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_article_author_alter_article_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatpeoplesay',
            name='postIt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatpeoplesay',
            name='saveDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 22, 16, 15, 16, 567551, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
