# Generated by Django 4.2.3 on 2024-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_whatpeoplesay_postit_whatpeoplesay_savedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatpeoplesay',
            name='saveDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
