# Generated by Django 5.0.1 on 2024-01-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_whatpeoplesay_savedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='x', null=True, verbose_name='Slug'),
        ),
    ]
