# Generated by Django 5.0.1 on 2024-01-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
