# Generated by Django 5.0.1 on 2024-01-24 20:38

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
