# Generated by Django 5.0.1 on 2024-01-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_article_options_alter_article_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
