# Generated by Django 5.0.1 on 2024-01-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='categoryArticles', to='post.category', verbose_name='Les Catégories'),
        ),
        migrations.AlterField(
            model_name='whatpeoplesay',
            name='content',
            field=models.TextField(max_length=246, verbose_name='Avis'),
        ),
        migrations.AlterField(
            model_name='whatpeoplesay',
            name='postIt',
            field=models.BooleanField(default=False, verbose_name='A poster'),
        ),
        migrations.AlterField(
            model_name='whatpeoplesay',
            name='whoSaid',
            field=models.CharField(max_length=64, verbose_name='Auteur'),
        ),
    ]
