# Generated by Django 5.0.1 on 2024-01-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_article_category_alter_whatpeoplesay_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='whichArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleComments', to='post.article', verbose_name='Article'),
        ),
    ]
