# Generated by Django 5.0.1 on 2024-02-08 18:54

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_remove_comment_canbeposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
