# Generated by Django 5.0.1 on 2024-02-08 21:34

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
