# Generated by Django 5.0.1 on 2024-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
