# Generated by Django 5.0.1 on 2024-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_article_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='online',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
